export default [
  { id: 1, name: "AAPS", types: "opshop", description: "descript" },
  { id: 2, name: "ADRA", types: "opshop", description: "descript" },
  {
    id: 3,
    name: "Australian Red Cross",
    types: "opshop",
    description: "descript",
  },
  {
    id: 4,
    name: "Brotherhood of St. Laurence",
    types: "opshop",
    description: "descript",
  },
  { id: 5, name: "Doncare", types: "opshop", description: "descript" },
  {
    id: 6,
    name: "Epilepsy Foundation",
    types: "opshop",
    description: "descript",
  },
  {
    id: 7,
    name: "Family Life",
    types: "opshop",
    description: "descript",
  },
  {
    id: 8,
    name: "Helping Hands Mission Inc.",
    types: "opshop",
    description: "descript",
  },
  {
    id: 9,
    name: "Lions Club ",
    types: "opshop",
    description: "descript",
  },
  {
    id: 10,
    name: "MS Community Shop",
    types: "opshop",
    description: "descript",
  },
  {
    id: 11,
    name: "Mister Minit",
    types: "repair",
    description: "descript",
  },
  {
    id: 12,
    name: "Ozwinds",
    types: "opshop",
    description: "descript",
  },
  {
    id: 13,
    name: "Posh Opp Shoppe",
    types: "opshop",
    description: "descript",
  },
  { id: 14, name: "RSPCA", types: "opshop", description: "descript" },
  {
    id: 15,
    name: "SCRGroup Clothing",
    types: "recycling",
    description: "descript",
  },
  {
    id: 16,
    name: "Sacred Heart Mission",
    types: "opshop",
    description: "descript",
  },
  {
    id: 17,
    name: "Salvos Stores",
    types: "opshop",
    description: "descript",
  },
  {
    id: 18,
    name: "Save the Children",
    types: "opshop",
    description: "descript",
  },
  { id: 19, name: "Savers", types: "opshop", description: "descript" },
  {
    id: 20,
    name: "Shoe Express",
    types: "repair",
    description: "descript",
  },
  {
    id: 21,
    name: "Shoe Guy",
    types: "repair",
    description: "descript",
  },
  {
    id: 22,
    name: "Storehouse Thrift",
    types: "opshop",
    description: "descript",
  },
  {
    id: 23,
    name: "The Salvation Army",
    types: "opshop",
    description: "descript",
  },
  { id: 24, name: "VMCH", types: "opshop", description: "descript" },
  {
    id: 25,
    name: "Vinnies",
    types: "opshop",
    description: "descript",
  },
  {
    id: 26,
    name: "Acland St Pop Up",
    types: "opshop",
    description: "descript",
  },
  {
    id: 27,
    name: "All Sorts",
    types: "opshop",
    description: "descript",
  },
  {
    id: 28,
    name: "All Souls",
    types: "opshop",
    description: "descript",
  },
  {
    id: 29,
    name: "Amaroo Neighbourhood Centre",
    types: "opshop",
    description: "descript",
  },
  {
    id: 30,
    name: "Angliss Gully",
    types: "opshop",
    description: "descript",
  },
  {
    id: 31,
    name: "Animal Aid",
    types: "opshop",
    description: "descript",
  },
  {
    id: 32,
    name: "Australian Clothing Recyclers",
    types: "opshop",
    description: "descript",
  },
  {
    id: 33,
    name: "Chapel Street Bazaar",
    types: "opshop",
    description: "descript",
  },
  {
    id: 34,
    name: "St Stephen's",
    types: "opshop",
    description: "descript",
  },
  {
    id: 35,
    name: "Tamminya House",
    types: "opshop",
    description: "descript",
  },
  {
    id: 36,
    name: "The Ashy",
    types: "opshop",
    description: "descript",
  },
  {
    id: 37,
    name: "The Holland Foundation",
    types: "opshop",
    description: "descript",
  },
  {
    id: 38,
    name: "The Mustard Tree",
    types: "opshop",
    description: "descript",
  },
  { id: 39, name: "Toorak", types: "opshop", description: "descript" },
  {
    id: 40,
    name: "Waverley Antique Bazaar",
    types: "opshop",
    description: "descript",
  },
  {
    id: 41,
    name: "Williamstown Hospital",
    types: "opshop",
    description: "descript",
  },
  {
    id: 42,
    name: "YES OP SHOP",
    types: "opshop",
    description: "descript",
  },
  {
    id: 43,
    name: "Yours Now Mine",
    types: "opshop",
    description: "descript",
  },
  {
    id: 44,
    name: "Ace Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 45,
    name: "Alexander' Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 46,
    name: "Andrew Michaels Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 47,
    name: "Ara's Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 48,
    name: "Arthur's Camberwell Market Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 49,
    name: "Ashburton Shoe Repairs & Clothing Alterations",
    types: "repair",
    description: "descript",
  },
  {
    id: 50,
    name: "Bellbird Cobbler",
    types: "repair",
    description: "descript",
  },
  {
    id: 51,
    name: "Bustop Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 52,
    name: "St. Kilda Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 53,
    name: "Tailor To Clothing Alterations",
    types: "repair",
    description: "descript",
  },
  {
    id: 54,
    name: "The Bespoke Corner Tailors Melbourne",
    types: "repair",
    description: "descript",
  },
  {
    id: 55,
    name: "The Cobbler",
    types: "repair",
    description: "descript",
  },
  {
    id: 56,
    name: "The Cobblers Last",
    types: "repair",
    description: "descript",
  },
  {
    id: 57,
    name: "The Hide on Cobblers Creek",
    types: "repair",
    description: "descript",
  },
  {
    id: 58,
    name: "Town & Country Cobbler Shop",
    types: "repair",
    description: "descript",
  },
  {
    id: 59,
    name: "Universal Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 60,
    name: "Urban Sole Shoe Repairs & Key Cutting",
    types: "repair",
    description: "descript",
  },
  {
    id: 61,
    name: "Warrnambool shoe repair and cobbler",
    types: "repair",
    description: "descript",
  },
  {
    id: 62,
    name: "Williamstown Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 63,
    name: "Workin Clobber",
    types: "repair",
    description: "descript",
  },
  {
    id: 64,
    name: "Australian Recycled Clothing",
    types: "recycling",
    description: "descript",
  },
  {
    id: 65,
    name: "Blackburn Clothing Dropoff Hub",
    types: "recycling",
    description: "descript",
  },
  {
    id: 66,
    name: "Charity Bin",
    types: "donation",
    description: "descript",
  },
  {
    id: 67,
    name: "Charity clothing Bin",
    types: "donation",
    description: "descript",
  },
  {
    id: 68,
    name: "Chris The Cobbler",
    types: "repair",
    description: "descript",
  },
  {
    id: 69,
    name: "Clarrie the Cobbler",
    types: "repair",
    description: "descript",
  },
  {
    id: 70,
    name: "Clayton Bargain Centre",
    types: "opshop",
    description: "descript",
  },
  {
    id: 71,
    name: "Clothing 4 Dawah Warehouse",
    types: "donation",
    description: "descript",
  },
  {
    id: 72,
    name: "Cobble Craft",
    types: "repair",
    description: "descript",
  },
  {
    id: 73,
    name: "Cobbler Ferrare",
    types: "repair",
    description: "descript",
  },
  {
    id: 74,
    name: "Cobbler Plus",
    types: "repair",
    description: "descript",
  },
  {
    id: 75,
    name: "Cobbler Plus & Watchworks",
    types: "repair",
    description: "descript",
  },
  {
    id: 76,
    name: "Cobbler Station",
    types: "repair",
    description: "descript",
  },
  {
    id: 77,
    name: "Cobblers of Kew",
    types: "repair",
    description: "descript",
  },
  {
    id: 78,
    name: "Cobblers Xtra",
    types: "repair",
    description: "descript",
  },
  { id: 79, name: "CoCO's", types: "opshop", description: "descript" },
  {
    id: 80,
    name: "Collins Place Cobbler",
    types: "repair",
    description: "descript",
  },
  {
    id: 81,
    name: "Condello's Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 82,
    name: "Croydon Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 83,
    name: "Donation Box",
    types: "donation",
    description: "descript",
  },
  {
    id: 84,
    name: "Donation clothing centre",
    types: "donation",
    description: "descript",
  },
  {
    id: 85,
    name: "Epilepsy Foundation",
    types: "opshop",
    description: "descript",
  },
  { id: 86, name: "Evans", types: "repair", description: "descript" },
  {
    id: 87,
    name: "Frank Condello Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 88,
    name: "George The Cobbler",
    types: "repair",
    description: "descript",
  },
  {
    id: 89,
    name: "Glenferrie Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 90,
    name: "Greeves St.",
    types: "opshop",
    description: "descript",
  },
  {
    id: 91,
    name: "Gregory's Bag & Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 92,
    name: "Gumtree seller",
    types: "opshop",
    description: "descript",
  },
  {
    id: 93,
    name: "Habitat for Humanity",
    types: "opshop",
    description: "descript",
  },
  {
    id: 94,
    name: "Heelsville Shoe Repairs & Birkenstock Sales",
    types: "repair",
    description: "descript",
  },
  {
    id: 95,
    name: "Hills Church",
    types: "opshop",
    description: "descript",
  },
  {
    id: 96,
    name: "HOPE Community",
    types: "opshop",
    description: "descript",
  },
  {
    id: 97,
    name: "Hunter Gatherer Fitzroy",
    types: "opshop",
    description: "descript",
  },
  {
    id: 98,
    name: "Hunter Seeker",
    types: "opshop",
    description: "descript",
  },
  {
    id: 99,
    name: "Kilmany",
    types: "opshop",
    description: "descript",
  },
  {
    id: 100,
    name: "Kindilan",
    types: "opshop",
    description: "descript",
  },
  {
    id: 101,
    name: "Klinger Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  { id: 102, name: "Knox", types: "opshop", description: "descript" },
  {
    id: 103,
    name: "Lifeline",
    types: "opshop",
    description: "descript",
  },
  {
    id: 104,
    name: "Lifeline Warehouse",
    types: "opshop",
    description: "descript",
  },
  {
    id: 105,
    name: "Lou's Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 106,
    name: "Main Street Shoe Repair",
    types: "repair",
    description: "descript",
  },
  {
    id: 107,
    name: "Manfred's Shoe Lounge",
    types: "repair",
    description: "descript",
  },
  {
    id: 108,
    name: "Master Cobbler",
    types: "repair",
    description: "descript",
  },
  {
    id: 109,
    name: "mecwacare Hawthorn",
    types: "opshop",
    description: "descript",
  },
  {
    id: 110,
    name: "Melbourne City Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 111,
    name: "Monash Rotary",
    types: "opshop",
    description: "descript",
  },
  {
    id: 112,
    name: "Monbulk Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 113,
    name: "Mordialloc",
    types: "opshop",
    description: "descript",
  },
  {
    id: 114,
    name: "Mt Eliza Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 115,
    name: "Newport Shoe Repair & Leather Goods Service",
    types: "repair",
    description: "descript",
  },
  {
    id: 116,
    name: "Once were new",
    types: "opshop",
    description: "descript",
  },
  {
    id: 117,
    name: "OzChild",
    types: "opshop",
    description: "descript",
  },
  {
    id: 118,
    name: "Paravin Charity Bin",
    types: "donation",
    description: "descript",
  },
  {
    id: 119,
    name: "Parish Bargain Shop",
    types: "opshop",
    description: "descript",
  },
  {
    id: 120,
    name: "Peter's Multi Services",
    types: "repair",
    description: "descript",
  },
  {
    id: 121,
    name: "Quick Shoe Repairs",
    types: "repair",
    description: "descript",
  },
  {
    id: 122,
    name: "Rekaris Shoe Repair",
    types: "repair",
    description: "descript",
  },
  {
    id: 123,
    name: "Rocky The Cobbler Shoe Repairer",
    types: "repair",
    description: "descript",
  },
  {
    id: 124,
    name: "Rosanna Op Shop by Kids First",
    types: "opshop",
    description: "descript",
  },
  {
    id: 125,
    name: "Rotary Clothesline",
    types: "opshop",
    description: "descript",
  },
  {
    id: 126,
    name: "Rotary Recycle",
    types: "opshop",
    description: "descript",
  },
  {
    id: 127,
    name: "Rotary Rummage",
    types: "opshop",
    description: "descript",
  },
  {
    id: 128,
    name: "Sally's Thrift Shop",
    types: "opshop",
    description: "descript",
  },
  {
    id: 129,
    name: "Scholler Shoe Repair",
    types: "repair",
    description: "descript",
  },
  {
    id: 130,
    name: "Secondo Boutique",
    types: "opshop",
    description: "descript",
  },
  {
    id: 131,
    name: "Serious Recycling",
    types: "opshop",
    description: "descript",
  },
  {
    id: 132,
    name: "Sien Clothing",
    types: "repair",
    description: "descript",
  },
  {
    id: 133,
    name: "Sole To Sole Shoe Repair & Locksmith",
    types: "repair",
    description: "descript",
  },
  {
    id: 134,
    name: "Soul Man",
    types: "repair",
    description: "descript",
  },
  {
    id: 135,
    name: "Spot On Shoe repair engraving key cutting watch repairServices",
    types: "repair",
    description: "descript",
  },
  {
    id: 136,
    name: "St Aidans",
    types: "opshop",
    description: "descript",
  },
  {
    id: 137,
    name: "St Augustine's Southern",
    types: "opshop",
    description: "descript",
  },
  {
    id: 138,
    name: "St James",
    types: "opshop",
    description: "descript",
  },
  {
    id: 139,
    name: "St Kilda Gatehouse Inc.",
    types: "donation",
    description: "descript",
  },
  {
    id: 140,
    name: "Textile Recyclers Australia",
    types: "recycling",
    description: "descript",
  },
  {
    id: 141,
    name: "UPPAREL",
    types: "recycling",
    description: "descript",
  },
  {
    id: 142,
    name: "Yarra Recycling Centre",
    types: "recycling",
    description: "descript",
  },
  {
    id: 143,
    name: "Clothes Recycling Bins",
    types: "recycling",
    description: "descript",
  },
  {
    id: 144,
    name: "Clothing & Household",
    types: "recycling",
    description: "descript",
  },
  {
    id: 145,
    name: "Clothing and Small Electrical Recycling bins",
    types: "recycling",
    description: "descript",
  },
  {
    id: 146,
    name: "Clothing Recycle Bin",
    types: "recycling",
    description: "descript",
  },
  {
    id: 147,
    name: "Clothing Recyclers",
    types: "recycling",
    description: "descript",
  },
  {
    id: 148,
    name: "Clothing Recycling bin, rear of Greythorn Grocer",
    types: "recycling",
    description: "descript",
  },
  {
    id: 149,
    name: "Clothing recycling bins",
    types: "recycling",
    description: "descript",
  },
  {
    id: 150,
    name: "Give your clothes a second Life",
    types: "recycling",
    description: "descript",
  },
  {
    id: 151,
    name: "Oz clothes recycling",
    types: "recycling",
    description: "descript",
  },
  {
    id: 152,
    name: "SCR Group",
    types: "recycling",
    description: "descript",
  },
  {
    id: 153,
    name: "Shred-X Secure Destruction Melbourne",
    types: "recycling",
    description: "descript",
  },
  {
    id: 154,
    name: "Small Electrical and Clothing Recycling Bin",
    types: "recycling",
    description: "descript",
  },
]
